import angular from 'angular';

// Import our app config files
import constants from './config/app.constants';
import appComponent from './app.component';
import appRun from './config/app.run';
import 'angular-ui-router';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './layout';
// import './components';
import './home';
import './services';


// Create and bootstrap application
const requires = [
    'ui.router',
    'templates',
    'app.layout',
    'app.home',
    // 'app.components',
    'app.services'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('MyConfig', constants);

angular.module('app').component('app', appComponent);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
    strictDi: true
});
